# Problem set 2 : Computational methods for Economists Fall-2021


# Part 1: Standard Library

# Problem 1

In [1]:
L = [100,200,300,400,500,600,700]
print(L)

[100, 200, 300, 400, 500, 600, 700]


In [2]:
def my_function(L):
    return ((min(L)), (max(L)), sum (L)/len(L))
print (my_function(L))


(100, 700, 400.0)


# Problem 2

Integer:

In [3]:
int_1 = 50
int_2 = int_1
int_2 = 100
int_1 == int_2


False

 Integers are not mutable since both objects are not same.

String:


In [4]:
str_1 = 'a'
str_2 = str_1
str_2 = 'b'
str_1 == str_2


False

So strings are also immutable

List:

In [5]:
list_1 = [5, 10, 15, 'Micro', 'Macro']
list_2 = list_1
list_2[1] = 20
list_1 == list_2

True

lists are mutable since both objects are the same.

Tuple:

In [6]:
tuple_1 = (5, 10, 15, 'Micro', 'Macro')
tuple_2 = tuple_1
tuple_2 += ('Economics',)
tuple_1 == tuple_2

False

Tuples are immutable since the objects are not same.

Set:

In [7]:
set_1 = {10, 20, 30, 'a' 'b'}
set_2 = set_1
set_2.remove(20)
set_1==set_2

True

Set are mutable since both objects are the same.

# problem 3

In [8]:
import calculator as calc

In [9]:
from math import sqrt

In [10]:
def hyp(a, b):
    return sqrt(calc.add(calc.multi(a, a), calc.multi(b, b)))

In [11]:
hyp(5,12)

13.0

# Part 2 - Introductory to Numpy

# Problem 1

In [12]:
import numpy as np

In [13]:
def matproduct():
    A = np.array( [ [3, -1, 4],[1, 5, -9] ] )
    B = np.array([ [ 2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3] ] )
    
    return A @ B

In [14]:
matproduct()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

# Problem 2

In [15]:
def func():
    A = np.array( [ [3, 1, 4],[1, 5, 9],[-5, 3, 1] ] )
    
    return -(A @ A @ A) + (9 * (A @ A)) - (15 * A)

In [16]:
func()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Problem 5

In [17]:
import numpy as np
def func():
    A = np.array( [ [0, 2, 4], [1, 3, 5] ] )
    B = np.array( [ [3, 0, 0], [3, 3, 0], [3, 3, 3] ] )
    C = np.array( [ [-2, 0, 0], [0, -2, 0], [0, 0, -2] ] )
    
    row1 = np.column_stack((np.zeros((3,3)), A.T, np.eye(3)))
    row2 = np.column_stack((A, np.zeros((2,2)), np.zeros_like(A)))
    row3 = np.column_stack((B, np.zeros_like(A.T), C))
    newfunc = np.concatenate((row1, row2, row3))
    
    return newfunc

In [18]:
func()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

# Part 3 - Object-Oriented Programming

# Problem 1

In [19]:
#1. constructor modification
class Backpack:
    '''
    A Backpack object class. Has a name, color,  list of contents, and maximum size of the contents.

    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        contents (list): the contents of the backpack.
        max_size (int) : the maximum size/number of the contents.
        

    '''
    def __init__(self, name, color, max_size = 5): # this function is the constructor.
        
        ''' Set the name, initialize an empty list of contents, set the color and
        set a default maximum number of items.
        
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum number of items the backpack can contain.
        '''

        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
     
    #2. modification of put() method
    
    def put(self, item):
        
        '''
        Adds an item to the backpack.
        
        Args:
            item (str): name of item to be added to the backpack
            
            Returns:
            "No Room!" if there are already max_size items or more.
        '''
        
        if len(self.contents) >= 5:
            print("No room!")
        
        else:
            self.contents.append(item)
    
    def take(self, item):
        '''
        Takes an item out of the backpack.
        
        Args:
            item (str): name of the item to be taken out of the backpack
            
        Returns:
            Nothing
        '''
        self.contents.remove(item)
    
    #3. reset contents to an empty list
    
    def dump(self):
        '''
        Empties all of the contents of the backpack.
        
        Args:
            None.
        
        Returns:
            Nothing.
        '''
        self.contents = []

In [20]:
def test_backpack():
    testpack = Backpack("Barry","black")
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
    print("Contents:", testpack.contents)

In [21]:
test_backpack()

Contents: ['pencil', 'pen', 'paper', 'computer']


# Problem 2

In [22]:
class Jetpack(Backpack):
    '''
    A Jetpack object class. Inherits from the Backpack class.

    Attributes: 
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the maximum number of items the backpack can contain.
        contents (list): the contents of the backpack.
        fuel (int): the amount of fuel in the tank.
    '''
    def __init__(self, name, color, max_size = 2, fuel=10 ):
        '''
        Set the name, initialize an empty list of contents, set a color, set a default
        maximum number of items, and set a default amount of fuel.
        
        Args:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum number of items the backpack can contain (default = 2).
            fuel (int): the amount of fuel in the tank (default =10).
        '''
        
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
    
    def fly(self, burned_fuel):
        '''
        Flies and burns fuel if there is enough fuel to burn the specified amount.
        
        Args:
            burned_fuel (int): amount of fuel to be burned
            
        Returns:
            "Not enough fuel!" if the amount entered is greater than the amount in the tank (i.e. 
            the number in "fuel.")
        '''
        if burned_fuel > self.fuel:
            print("Not enough fuel!")
            
       
    def dump(self):
        '''
        Empties all the contents of the backpack and all of the fuel.
        
        Args:
            None.
        
        Returns:
            Nothing.
        '''
        self.contents = []
        self.fuel = 0

In [23]:
def test_Jetpack():
    testpack = Backpack("Barry","black")
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
    print("Contents:", testpack.contents)

In [24]:
test_Jetpack()

Contents: ['pencil', 'pen', 'paper', 'computer']
